import React,{useEffect,useRef,useState} from 'react';
import {ArchiveRestore,LoaderCircle,RefreshCw,ShieldCheck,Trash2,UserPlus,Users} from 'lucide-react';

async function request(path,body){const response=await fetch('/api'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),data=await response.json();if(response.status===401)window.dispatchEvent(new Event('badr-auth-expired'));if(!response.ok)throw Error(data.error);return data;}
const when=value=>new Date(value).toLocaleString('ar-EG',{dateStyle:'medium',timeStyle:'short'});

export function UsersPage({currentUser}){
 const [users,setUsers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{setUsers(await request('/admin/users'));}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function add(event){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));setBusy(true);setError('');setNotice('');try{await request('/admin/users',values);form.reset();setNotice('تمت إضافة المستخدم');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function changeStatus(user){const activating=!!user.deleted_at;if(!activating&&!window.confirm(`سيتم تعطيل حساب ${user.name} مع الاحتفاظ بسجله. هل تريد المتابعة؟`))return;setError('');try{await request('/admin/users/'+user.id+'/status',{active:activating});setNotice(activating?'تمت إعادة تفعيل المستخدم':'تم تعطيل المستخدم وحفظه في السجل');await load();}catch(e){setError(e.message);}}
 return <div className="admin-layout"><section className="panel admin-form"><div className="panel-title"><h2><UserPlus size={19}/>إضافة مستخدم</h2></div><form className="form-content" onSubmit={add}><label>اسم الموظف<input name="name" required maxLength={80}/></label><label>اسم الدخول<input name="username" required minLength={3} maxLength={40} dir="ltr"/></label><label>كلمة المرور<input name="password" type="password" required minLength={8} maxLength={128} dir="ltr"/></label><label>نوع المستخدم<select name="role" defaultValue="user"><option value="user">مستخدم عادي</option><option value="admin">مدير</option></select></label>{error&&<div className="error admin-message">{error}</div>}{notice&&<div className="success-message">{notice}</div>}<button className="primary" disabled={busy}>{busy?'جارٍ الحفظ...':'إضافة المستخدم'}</button></form></section><section className="panel admin-list"><div className="panel-title"><h2><Users size={19}/>المستخدمون <span>{users.length}</span></h2></div><div className="table-wrap"><table><thead><tr><th>المستخدم</th><th>اسم الدخول</th><th>الصلاحية</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className={user.deleted_at?'muted-row':''}><td><b>{user.name}</b></td><td dir="ltr">{user.username}</td><td><span className={'badge '+(user.role==='admin'?'admin-badge':'gray')}>{user.role==='admin'?'مدير':'مستخدم'}</span></td><td>{user.deleted_at?<span className="badge red">معطّل</span>:<span className="badge green">فعال</span>}</td><td><button className={user.deleted_at?'restore-button':'soft-delete-button'} disabled={user.id===currentUser.id} onClick={()=>changeStatus(user)}>{user.deleted_at?<><ArchiveRestore size={15}/>تفعيل</>:<><Trash2 size={15}/>تعطيل</>}</button></td></tr>)}</tbody></table></div></section></div>;
}

export function AuditPage(){
 const [logs,setLogs]=useState([]),[total,setTotal]=useState(0),[hasMore,setHasMore]=useState(false),[archive,setArchive]=useState({patients:[],departments:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false);
 const scrollRoot=useRef(null),sentinel=useRef(null);
 async function load(reset=true){if(!reset&&(loading||loadingMore||!hasMore))return;reset?setLoading(true):setLoadingMore(true);setError('');try{const offset=reset?0:logs.length;if(reset){const [page,deleted]=await Promise.all([request(`/admin/audit?limit=30&offset=${offset}`),request('/admin/archive')]);setLogs(page.logs);setTotal(page.total);setHasMore(page.has_more);setArchive(deleted);}else{const page=await request(`/admin/audit?limit=30&offset=${offset}`);setLogs(previous=>[...previous,...page.logs]);setTotal(page.total);setHasMore(page.has_more);}}catch(e){setError(e.message);}finally{setLoading(false);setLoadingMore(false);}}
 useEffect(()=>{load(true);},[]);
 useEffect(()=>{const node=sentinel.current,root=scrollRoot.current;if(!node||!root||!hasMore||loading||loadingMore)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)load(false);},{root,rootMargin:'180px'});observer.observe(node);return()=>observer.disconnect();},[hasMore,loading,loadingMore,logs.length]);
 async function restore(type,item){setError('');try{await request(`/admin/${type}/${item.id}/restore`,{});await load(true);}catch(e){setError(e.message);}}
 return <div className="audit-layout">{error&&<div className="error">{error}</div>}<section className="panel"><div className="panel-title"><h2><ShieldCheck size={19}/>سجل النشاط <span>{logs.length} من {total}</span></h2><button className="secondary compact" onClick={()=>load(true)} disabled={loading||loadingMore}><RefreshCw size={15}/>تحديث</button></div><div className="table-wrap audit-table" ref={scrollRoot}><table><thead><tr><th>المستخدم</th><th>العملية</th><th>التاريخ والوقت</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td><b>{log.user_name}</b><small dir="ltr">@{log.username}</small></td><td>{log.description}</td><td>{when(log.created_at)}</td></tr>)}</tbody></table>{!logs.length&&!loading&&<div className="empty"><h3>لا توجد عمليات مسجلة بعد</h3></div>}<div className="audit-sentinel" ref={sentinel}>{hasMore?<button onClick={()=>load(false)} disabled={loadingMore}>{loadingMore?<><LoaderCircle className="spin" size={15}/>جارٍ تحميل 30 عملية...</>:'تحميل 30 عملية إضافية'}</button>:logs.length>0&&<span>تم عرض كل العمليات</span>}</div></div></section><section className="panel archive-panel"><div className="panel-title"><h2><ArchiveRestore size={19}/>المحذوفات المؤقتة</h2></div><div className="archive-groups"><div><h3>ملفات المرضى ({archive.patients.length})</h3>{archive.patients.map(patient=><article key={patient.id}><span><b>{patient.name}</b><small dir="ltr">{patient.medical_number}</small></span><button className="restore-button" onClick={()=>restore('patients',patient)}><ArchiveRestore size={14}/>استعادة</button></article>)}{!archive.patients.length&&<p>لا توجد ملفات مرضى محذوفة.</p>}</div><div><h3>الأقسام ({archive.departments.length})</h3>{archive.departments.map(department=><article key={department.id}><span><b>{department.name}</b><small>{department.capacity} سرير</small></span><button className="restore-button" onClick={()=>restore('departments',department)}><ArchiveRestore size={14}/>استعادة</button></article>)}{!archive.departments.length&&<p>لا توجد أقسام محذوفة.</p>}</div></div></section></div>;
}
